### ISSUE TITLE
Display issues when using Thick line width

### ISSUE THREAD

**Issue by L0Lock** [Hasib345/Blender-Text-Editor-Essentials#4]
Default (thin):
![image](https://github.com/Hasib345/Blender-Text-Editor-Essentials/assets/16049822/185513a8-b184-4e27-bc0a-74c38f6e6b51)

Thick:
![image](https://github.com/Hasib345/Blender-Text-Editor-Essentials/assets/16049822/d7081a64-156c-474f-9f69-521ac12ea342)

Highlights gets way bigger than the original text and offset upward. Indent guides and whitespaces are offset..

**Comment by Hasib345** [comment]
This is an scaling problem . This is caused as the thick option was not taken in to account when drawing the highligts

**Comment by Hasib345** [comment]
I will have this issue fixed in next update

**Comment by Hasib345** [comment]
This issue is fixed in latest relaese so I will be closing this comment . Have a good day .  Thank you
